<?php
/**
 * Implements hook_menu().
 * Responed to url handling for lr_sso_menu module.
 *
 * @return array An array of menu items
 */

module_load_include('php', 'lr_social_login', 'LoginRadiusSDK/SocialLogin/SocialLoginAPI');
module_load_include('php', 'lr_social_login', 'LoginRadiusSDK/LoginRadius');
module_load_include('php', 'lr_social_login', 'LoginRadiusSDK/LoginRadiusException');
module_load_include('php', 'lr_social_login', 'LoginRadiusSDK/Clients/IHttpClient');
module_load_include('php', 'lr_social_login', 'LoginRadiusSDK/Clients/DefaultHttpClient');


use \LoginRadiusSDK\LoginRadius;
use \LoginRadiusSDK\LoginRadiusException;
use \LoginRadiusSDK\SocialLogin\SocialLoginAPI;

module_load_include('php', 'lr_social_login', 'customhttpclient');
global $apiClient_class;
$apiClient_class = 'CustomHttpClient';

function lr_sso_menu() {
  $file_path = drupal_get_path('module', 'lr_sso');
  $items['admin/config/people/userregistration/sso'] = array(
    'title' => 'sso',
    'description' => 'Single Sign On',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lr_sso_settings_form'),
    'access arguments' => array('administer sso'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 7,
    'file path' => $file_path,
    'file' => 'includes/lr_sso.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 *
 * Responed to Define user permissions.
 *
 * @return array An array of permission settings
 */
function lr_sso_permission() {
  return array(
    'administer sso' => array(
      'title' => t('Administer SSO settings'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Add required sso js files to page.
 *
 * @param $vars
 * @param $hook
 */
function lr_sso_preprocess_page(&$vars, $hook) {
  global $user;
  $site_name = variable_get('lr_sso_site_name');
  if (variable_get('lr_sso_enable') == 1 && !empty($site_name)) {
    if (drupal_is_front_page()) {
      $GLOBALS['conf']['cache'] = FALSE;
    }
    $path = parse_url(url('', array('absolute' => TRUE)));
    $sso_path = $path['path'];
    drupal_add_js('if (window.enable_social_invite != true) {
    document.write("<scr"+"ipt src=//cdn.loginradius.com/hub/prod/js/LoginRadiusSSO.js><\/scr"+"ipt>");
}', array('type' => 'inline', 'scope' => 'footer', 'weight' => 1));

    drupal_add_js('
              if (window.LoginRadiusSSO) {
         var tokencookie = "lr-user--token";
         LoginRadiusSSO.setToken = function (token) {
        LoginRadiusSSO.Cookie.setItem(tokencookie, token, "' . $sso_path . '");}
      }   
        ', array('type' => 'inline', 'scope' => 'header', 'weight' => 4));

    if (variable_get('lr_user_logout') == 1) {
      variable_del('lr_user_logout');
      drupal_add_js('
    jQuery(document).ready(function () {
      if (window.LoginRadiusSSO && window.enable_social_invite != true) {
            LoginRadiusSSO.init("' . trim($site_name) . '", "' . $sso_path . '");
            LoginRadiusSSO.logout("' . url('', array('absolute' => TRUE)) . '")
          }
        });', array('type' => 'inline', 'scope' => 'header', 'weight' => 5));
    }
    else {
      if (!user_is_logged_in()) {
        if (!(variable_get('user_register') == 0 && variable_get('lr_social_login_enable_user_registration') == 0)) {
          $destination = drupal_get_destination();
          $callback = $destination['destination'];
          $query[] = array('destination' => $callback);
          drupal_add_js('
    jQuery(document).ready(function () {
      if (window.LoginRadiusSSO && window.enable_social_invite != true) {
      var apidomain = "https://api.loginradius.com";
            LoginRadiusSSO.init("' . trim($site_name) . '", "' . $sso_path . '");
             var str = window.location.href;
            if(str.indexOf("user/login") == -1) {
              if (!LoginRadiusRaaS.loginradiushtml5passToken) {
                   LoginRadiusRaaS.loginradiushtml5passToken = function (token) {
                       if (token) {
                        window.location = "' . url('user/login', array(
              'absolute' => TRUE,
              'query' => $query,
            )) . '";
                       }
                     }
                   }
             }
            LoginRadiusSSO.login("' . urldecode(lr_social_login_get_callback_url()) . '");
        }    
        });
        jQuery("#lr-loading").hide();
        ', array('type' => 'inline', 'scope' => 'header', 'weight' => 5));
        }
      }
      if (user_is_logged_in()) {
        $logout = urldecode(url('user/logout'));
        $logout = (strpos($logout, '?') == TRUE ? ($logout . '&notlogged=1') : ($logout . '?notlogged=1'));
        if (!(is_array($user->roles) && in_array('administrator', $user->roles))) {
          drupal_add_js('
    jQuery(document).ready(function () {
      if (window.LoginRadiusSSO && window.enable_social_invite != true) {
            LoginRadiusSSO.init("' . trim($site_name) . '", "' . $sso_path . '");
            LoginRadiusSSO.isNotLoginThenLogout("' . $logout . '");}
        });', array('type' => 'inline', 'scope' => 'header', 'weight' => 5));
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 *
 * @return array An associative array of theme hook information
 */
function lr_sso_theme() {
  $path = drupal_get_path('module', 'lr_sso') . '/theme';
  $theme = array(
    'sso_login' => array(
      'template' => 'sso_login',
      'render element' => 'form',
      'path' => $path,
    ),

  );
  return $theme;
}

/**
 * When user logout the set variable.
 *
 * @param $account
 */
function lr_sso_user_logout($account) {
  $site_name = variable_get('lr_sso_site_name');
  if (variable_get('lr_sso_enable') == 1 && !isset($_REQUEST['notlogged']) && !empty($site_name)) {
    variable_set('lr_user_logout', 1);
  }
}

/**
 * Check valid token retrieved to perform sso.
 *
 * @param $token
 * @return string
 */
function lr_sso_check_lrtoken_valid($token) {
  if (!empty($token)) {  

    $apiKey = trim(variable_get('lr_social_login_apikey'));
    $secret = trim(variable_get('lr_social_login_apisecret'));
    $socialLoginObject = new SocialLoginAPI($apiKey, $secret, array(
          'output_format' => TRUE,
          'authentication' => FALSE
        ));

    try {    
        $token = $socialLoginObject->exchangeAccessToken($token);            
      }
      catch (LoginRadiusException $e) {
          watchdog_exception('type', $e);
    }

    if ($token) {
      return $token;
    }
    $site_name = variable_get('lr_sso_site_name');
    $path = parse_url(url('', array('absolute' => TRUE)));
    $sso_path = $path['path'];
    drupal_add_js('
    jQuery(document).ready(function () {
      if (window.LoginRadiusSSO && window.enable_social_invite != true) {
            LoginRadiusSSO.init("' . trim($site_name) . '", "' . $sso_path . '");
            LoginRadiusSSO.logout("' . url('', array('absolute' => TRUE)) . '")
          }
        });', array('type' => 'inline', 'scope' => 'header', 'weight' => 5));
  }
}


